networks:
  asw_network:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.254

services:
  client:
    image: andreabiagini5/aswclient
    container_name: aswclient
    restart: always
    ports:
      - '80:4173'
    depends_on:
      - server
    environment:
      VITE_SERVER_IP: ${SERVER_IP}
      VITE_SERVER_PORT: ${SERVER_PORT}
      VITE_SERVER_PROTOCOL: ${SERVER_PROTOCOL}
    networks:
      asw_network:
        ipv4_address: 172.0.0.11

  server:
    image: andreabiagini5/aswserver
    container_name: aswserver
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_INTERNAL_PORT}'
    depends_on:
      - database
    environment:
      PORT: ${SERVER_INTERNAL_PORT}
      DB_APP_USERNAME: ${DB_APP_USERNAME}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PROTOCOL: ${DB_PROTOCOL}
      DB_IP: ${DB_IP}
      DB_PORT: ${DB_PORT}
      CLIENT_PROTOCOL: ${CLIENT_PROTOCOL}
      CLIENT_IP: ${CLIENT_IP}
      CLIENT_PORT: ${CLIENT_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      NODE_ENV: 'production'
    networks:
      asw_network:
        ipv4_address: ${SERVER_IP}

  database:
    image: mongo
    container_name: mongodb
    command: ${MONGODB_COMMAND}
    restart: always
    ports:
      - '${DB_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_APP_USERNAME: ${DB_APP_USERNAME}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongod.conf:/etc/mongod.conf
    networks:
      asw_network:
        ipv4_address: ${DB_IP}

volumes:
  mongo_data:
