networks:
  asw_network:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.254

services:
  client:
    build:
      context: ./src/client
      args:
        - VITE_SERVER_IP=${SERVER_IP}
        - VITE_SERVER_PORT=${SERVER_PORT}
        - VITE_SERVER_PROTOCOL=${SERVER_PROTOCOL}
    container_name: aswclient
    restart: always
    ports:
      - '80:80'
    depends_on:
      - server
    networks:
      asw_network:
        ipv4_address: 172.0.0.11
  server:
    image: andreabiagini5/aswserver
    container_name: aswserver
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_INTERNAL_PORT}'
    depends_on:
      - database
    environment:
      PORT: ${SERVER_INTERNAL_PORT}
      DB_APP_USERNAME: ${DB_APP_USERNAME}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PROTOCOL: ${DB_PROTOCOL}
      DB_IP: ${DB_IP}
      DB_PORT: ${DB_PORT}
    networks:
      asw_network:
        ipv4_address: ${SERVER_IP}

  database:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '${DB_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_APP_USERNAME: ${DB_APP_USERNAME}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js
    secrets:
      - mongo_root_password
    networks:
      asw_network:
        ipv4_address: ${DB_IP}

secrets:
  mongo_root_password:
    file: src/server/secrets/mongo_root_password.txt

volumes:
  mongo_data:
