networks:
  asw_network:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.254

services:
  client:
    image: andreabiagini5/aswclient
    build:
      context: ./src/client
      args:
        - VITE_SERVER_IP=172.0.0.11
        - VITE_SERVER_PROTOCOL=https
        - VITE_DOCKER=true
    container_name: aswclient
    restart: always
    ports:
      - '4173:80'
    depends_on:
      - server
    environment:
      VITE_SERVER_IP: 172.0.0.11
      VITE_SERVER_PROTOCOL: https
    networks:
      asw_network:

  server:
    image: andreabiagini5/aswserver
    container_name: aswserver
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      PORT: 3000
      DB_APP_USERNAME: ${DB_APP_USERNAME}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PROTOCOL: mongodb
      DB_IP: 172.0.0.12
      DB_PORT: 27017
      CLIENT_PROTOCOL: https
      CLIENT_IP: 172.0.0.11
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      NODE_ENV: 'production'
      DOCKER: true
    networks:
      asw_network:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - client
      - server
    networks:
      asw_network:
        ipv4_address: 172.0.0.11

  database:
    image: mongo
    container_name: database
    command: 'mongod --config /etc/mongod.conf'
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_APP_USERNAME: ${DB_APP_USERNAME}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongod.conf:/etc/mongod.conf
    networks:
      asw_network:
        ipv4_address: 172.0.0.12

volumes:
  mongo_data:
