networks:
  asw_network:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.254

services:
  server:
    image: andreabiagini5/aswserver
    container_name: aswserver
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      PORT: 3000
    networks:
      asw_network:
        ipv4_address: 172.0.0.10

  client:
    image: andreabiagini5/aswclient
    container_name: aswclient
    restart: always
    ports:
      - '4173:4173'
    depends_on:
      - server
      - database
    networks:
      asw_network:
        ipv4_address: 172.0.0.11

  database:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '${DB_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      asw_network:
        ipv4_address: ${DB_IP}

volumes:
  mongo_data:
