networks:
  asw_network:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.254

services:
  server:
    image: andreabiagini5/aswserver
    container_name: aswserver
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      PORT: 3000
      MONGO_USERNAME: asw-user
      MONGO_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: ASW-DB
      MONGO_IP: 172.0.0.12
    networks:
      asw_network:
        ipv4_address: 172.0.0.10
    secrets:
      - mongo_root_password

  client:
    image: andreabiagini5/aswclient
    container_name: aswclient
    restart: always
    ports:
      - '4173:4173'
    depends_on:
      - server
      - database
    networks:
      asw_network:
        ipv4_address: 172.0.0.11

  database:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
    volumes:
      - mongo_data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js
    secrets:
      - mongo_root_password
    networks:
      asw_network:
        ipv4_address: 172.0.0.12

secrets:
  mongo_root_password:
    file: src/server/secrets/mongo_root_password.txt

volumes:
  mongo_data:
