networks:
  asw_network:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.254

services:
  server:
    image: andreabiagini5/aswserver
    container_name: aswserver
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://admin:$(cat /run/secrets/mongo_root_password)@mongodb:27017/ASW-DB
    networks:
      asw_network:
        ipv4_address: 172.0.0.10

  client:
    image: andreabiagini5/aswclient
    container_name: aswclient
    restart: always
    ports:
      - '4173:4173'
    depends_on:
      - server
      - database
    networks:
      asw_network:
        ipv4_address: 172.0.0.11
  server:
    image: andreabiagini5/aswserver
    container_name: aswserver
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      PORT: 3000
      DB_APP_USERNAME: ${DB_APP_USERNAME}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PROTOCOL: ${DB_PROTOCOL}
      DB_IP: ${DB_IP}
      DB_PORT: ${DB_PORT}
    networks:
      asw_network:
        ipv4_address: 172.0.0.10

  database:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '${DB_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_APP_USERNAME: ${DB_APP_USERNAME}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      asw_network:
        ipv4_address: ${DB_IP}

secrets:
  mongo_root_password:
    file: src/server/secrets/mongo_root_password.txt

volumes:
  mongo_data:
