#!/bin/bash

if [ "$2" == "merge" ]; then
    # Get the current branch name
    current_branch=$(git rev-parse --abbrev-ref HEAD)

    # Get the branch being merged
    merged_branch=$(git name-rev --name-only $(git rev-parse MERGE_HEAD))

    # Write the custom commit message
    echo "chore: merge $current_branch with $merged_branch" > "$1"
fi

