name: ASW CI/CD

on:
  push:
    # branches:
    #   - dev
    #   - main
    #   - ci
  workflow_dispatch:

concurrency:
  group: "asw-ci-cd"
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: write

jobs:
  # changelog:
  #   runs-on: ubuntu-latest
  #   # needs: 
  #   #   - build
  #   #   - test
  #   name: Generate and Commit Changelog
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Set Git User Info
  #       run: |
  #         git config user.name 'GitHub Actions Bot'
  #         git config user.email 'actions@github.com'

  #     - name: Checkout main
  #       run: |
  #         git pull
  #         git checkout release
  #         git pull
  #         git pull origin dev -X theirs

  #     - name: Generate Changelog
  #       uses: smichard/conventional_changelog@2.0.0
  #       with:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Commit Changelog
  #       id: commit_changelog
  #       run: |
  #         git add CHANGELOG.md
  #         git commit -m "chore: updated CHANGELOG.md" || echo "No changes to commit"
  #         git push || echo "Failed to push changes"

  send-notification:
    runs-on: ubuntu-latest
    # needs: 
      # - build
      # - test
      # - changelog
    if: always()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Extract Branch Name
        id: vars
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Capture New Version
        run: |
          NEW_VERSION=$(git describe --tags --abbrev=0)
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Get Commit Message
        id: commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "COMMIT_MESSAGE=${COMMIT_MESSAGE}" >> $GITHUB_ENV

      - name: Determine Pipeline Status
        id: status
        run: |
          # if [[ "${{ needs.build.result }}" == "success" && "${{ needs.test.result }}" == "success" ]]; then
          #   if [[ "${{ needs.changelog.result }}" == "success" ]]; then
          echo "TITLE=# ✅New Release: ${{ env.NEW_VERSION }}" >> $GITHUB_ENV
          #   else
          #     echo "TITLE=# ⚠️Success without changelog update" >> $GITHUB_ENV
          #   fi
          # else
          #   echo "TITLE=# ❌Pipeline Failed" >> $GITHUB_ENV
          # fi

      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        with:
          args: |
            "${{ env.TITLE }}

            **Branch**: `${{ env.BRANCH_NAME }}`
            **Author**: ${{ github.actor }}
            **Commit**: `${{ env.COMMIT_MESSAGE }}`
            **Details**: [View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub Actions
          DISCORD_AVATAR: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
